apiVersion: v1
kind: Service
metadata:
  name: gullyscore-backend
  namespace: gullyscore
  labels:
    app.kubernetes.io/name: gullyscore-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gullyscore-backend
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
